### ISSUE TITLE
Cannot run generate.py

### ISSUE THREAD

**Issue by relt-1** [tloen/alpaca-lora#100]
I did `pip install -r requirements.txt` and then tried to run generate.py
I got this error
```
Traceback (most recent call last):
  File "C:\alpaca-lora-main\generate.py", line 2, in <module>
    from peft import PeftModel
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\peft\peft_model.py", line 22, in <module>
    from accelerate import dispatch_model, infer_auto_device_map
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\accelerate\accelerator.py", line 36, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\micha\AppData\Local\programs\python\python39\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
```

**Comment by relt-1** [comment]
I believe the issue is caused by tensorflow not having the module `tensorflow.io` for some reason.

**Comment by Zachary-Hamel** [comment]
Have you tried the following?

pip install tensorflow-io

**Comment by RThaweewat** [comment]
Install from requirements.txt in clean env suppose to prevent this issue, if it's not working pls try `pip install --upgrade tensorflow`
