### ISSUE TITLE
ValueError: Can't find config.json at 'tloen/alpaca-lora-7b'

### ISSUE THREAD

**Issue by candowu** [tloen/alpaca-lora#137]
i test in offline mode, and download the model file in cache dir, but i get follow errors.

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 33/33 [00:11<00:00,  2.92it/s]
Traceback (most recent call last):
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/peft/utils/config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1253, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/candowu/alpaca-lora-main/generate.py", line 36, in <module>
    model = PeftModel.from_pretrained(
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at 'tloen/alpaca-lora-7b'

**Comment by theUpsider** [comment]
For anyone wondering how to get the config in a local setup. Create the folders tloen/alpaca-lora-7b and put following file into it: https://huggingface.co/tloen/alpaca-lora-7b/blob/main/adapter_config.json

**Comment by avivples** [comment]
> For anyone wondering how to get the config in a local setup. Create the folders and put following file into it: https://huggingface.co/tloen/alpaca-lora-7b/blob/main/adapter_config.json

What folders should I create within the git repository folder?

**Comment by theUpsider** [comment]
> > For anyone wondering how to get the config in a local setup. Create the folders and put following file into it: https://huggingface.co/tloen/alpaca-lora-7b/blob/main/adapter_config.json
> 
> What folders should I create within the git repository folder?

I updated my comment. Basically the folders the error displays you.
