### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero when running generate.py

### ISSUE THREAD

**Issue by sloorp** [tloen/alpaca-lora#150]
I finished `finetuning.py` and now I am trying to run `generate.py` but I get ZeroDivisionError:

```
Traceback (most recent call last):
  File "\alpaca-lora-main\generate.py", line 36, in <module>
    model = PeftModel.from_pretrained(
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\peft_model.py", line 167, in from_pretrained
    max_memory = get_balanced_memory(
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\modeling.py", line 368, in get_balanced_memory
    per_gpu = module_sizes["1"] // (num_devices - 1 if low_zero else num_devices)
ZeroDivisionError: integer division or modulo by zero
```

Running on Windows. Anyone knows how to fix this?

**Comment by joshsimon7** [comment]
I am having the same issue. Did you find a solution?

**Comment by Wa-lead** [comment]
having the same issue
trying to run this GTX1080

**Comment by zoemaestra** [comment]
https://github.com/tloen/alpaca-lora/issues/260#issuecomment-1497794933
