### ISSUE TITLE
How do I change the finetune.py to work with the 'tloen/alpaca-lora-7b' model as the base model?

### ISSUE THREAD

**Issue by thihanmoekyaw** [tloen/alpaca-lora#160]
When I try to change the model to 'tloen/alpaca-lora-7b', it give me an error. Here is the full error:

```
(env) (python310) ubuntu@141-148-202-210:~/alpaca-lora$ python finetune.py\
>     --base_model 'tloen/alpaca-lora-7b'\
>     --data_path 'MY_DATASET.json'\
>     --output_dir 'lora-alpaca'

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/ubuntu/anaconda3/envs/python310/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Training Alpaca-LoRA model with params:
base_model: tloen/alpaca-lora-7b
data_path: MY_DATASET.json
output_dir: lora-alpaca
batch_size: 128
micro_batch_size: 4
num_epochs: 1
learning_rate: 0.0003
cutoff_len: 512
val_set_size: 19600
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: True

Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Traceback (most recent call last):
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/tloen/alpaca-lora-7b/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-641e1a94-0bde0256626107ef400d6582)

Entry Not Found for url: https://huggingface.co/tloen/alpaca-lora-7b/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/alpaca-lora/finetune.py", line 217, in <module>
    fire.Fire(train)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/alpaca-lora/finetune.py", line 78, in train
    model = LlamaForCausalLM.from_pretrained(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2170, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/ubuntu/alpaca-lora/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: tloen/alpaca-lora-7b does not appear to have a file named config.json. Checkout 'https://huggingface.co/tloen/alpaca-lora-7b/main' for available files.
```

How do I fix it so that it reads the proper config.json file?

**Comment by tloen** [comment]
Unfortunately `tloen/alpaca-lora-7b` is a LoRA adapter, not a base model.
