### ISSUE TITLE
An error was reported when run finetune.py

### ISSUE THREAD

**Issue by dsh54054** [tloen/alpaca-lora#179]
After installing the dependent environment, the following error was reported when running finetune. py. Does anyone know the reason or solution.

Traceback (most recent call last):
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/weights/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64215325-2e3532664720fddd7d7029a0)

Repository Not Found for url: https://huggingface.co/weights/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 47, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2170, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: weights is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by AngainorDev** [comment]
Looks like you gave a wrong parameter for base_model.

https://github.com/tloen/alpaca-lora#training-finetunepy

How did you invoke finetune.py ?

**Comment by dsh54054** [comment]
I referred to Example usage to  invoke the finetune.py: 
python generate.py \
    --load_8bit \
    --base_model 'decapoda-research/llama-7b-hf' \
    --lora_weights 'tloen/alpaca-lora-7b'

**Comment by LutaoChu** [comment]
@dsh54054 Do you solve the problem? I met the same problem

**Comment by dsh54054** [comment]
> @dsh54054 Do you solve the problem? I met the same problem

emmm，I found that the finetune. py script I used was too old. After using the latest version of the finetune. py script, the problem was resolved.
