### ISSUE TITLE
generate error by ziqingyang/chinese-alpaca-lora-7b

### ISSUE THREAD

**Issue by tensortkk** [tloen/alpaca-lora#220]
Here is the error:

Traceback (most recent call last):
  File "../generate.py", line 184, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "../generate.py", line 43, in main
    model = PeftModel.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 161, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/usr/local/lib/python3.8/dist-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1918, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49953, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
        size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49953, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).

**Comment by AngainorDev** [comment]
Are you sure you used the right (model, peft) couple?

Check your peft config json , `adapter_config.json` to make sure you used the correct base model for inference.

**Comment by AngainorDev** [comment]
This model is not a standard one, it comes with its own tokenizer
https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/tree/main
and has a dedicated repo with related doc
https://github.com/ymcui/Chinese-LLaMA-Alpaca

The error is likely related to the tokenizer mismatch.

**Comment by 12lxr** [comment]
请问这个问题该如何解决呢

**Comment by JhCircle** [comment]
Can you please tell me how to fix it? Thank you, sir.
