### ISSUE TITLE
Error: weight is on the meta device

### ISSUE THREAD

**Issue by askintution** [tloen/alpaca-lora#259]
I have 4 gpus, and i use the latest code. still have error: weight is on the meta device

find same problem in issues but no help. 
[How to combine: base model + trained lora back to HF model? · Issue #53 · tloen/alpaca-lora](https://github.com/tloen/alpaca-lora/issues/53)

Any help or debug method? 

The error list below:

Traceback (most recent call last):
  File "/data/home/test/nlp/alpaca-lora/finetune.py", line 277, in <module>
    fire.Fire(train)
  File "/home/xxx/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/xxx/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/xxx/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/home/test/nlp/alpaca-lora/finetune.py", line 110, in train
    model = LlamaForCausalLM.from_pretrained(
  File "/data/home/test/nlp/alpaca-lora/transformers/src/transformers/modeling_utils.py", line 2694, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
  File "/home/xxx/.local/lib/python3.9/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/xxx/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 471, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/xxx/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/xxx/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 244, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/xxx/.local/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 136, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on 3.

**Comment by rucieryi369** [comment]
I meet same question,  Can you tell me how to solve it ? Thanks

**Comment by wzko0** [comment]
Hello, I have the same problem, how to solve it?
