### ISSUE TITLE
AttributeError: 'MatmulLtState' object has no attribute 'memory_efficient_backward'

### ISSUE THREAD

**Issue by jzhao321** [tloen/alpaca-lora#271]
Git cloing from latest and running the following command.
```
python generate.py --load_8bit --base_model 'decapoda-research/llama-13b-hf' --lora_weights 'chansung/alpaca-lora-13b'
```
results in this error:
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
load_in_8bit
Loading checkpoint shards:   0%|                                                                                                                                                                                     | 0/41 [00:00<?, ?it/s]/home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/bitsandbytes/functional.py:158: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  else: return ct.c_void_p(A.data.storage().data_ptr())
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:30<00:00,  1.36it/s]
Downloading (…)/adapter_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 371/371 [00:00<00:00, 210kB/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wsluser/Work/alpaca-lora/generate.py:218 in <module>                                         │
│                                                                                                  │
│   215                                                                                            │
│   216                                                                                            │
│   217 if __name__ == "__main__":                                                                 │
│ ❱ 218 │   fire.Fire(main)                                                                        │
│   219                                                                                            │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/fire/core.py:141 in Fire          │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/fire/core.py:475 in _Fire         │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/fire/core.py:691 in               │
│ _CallAndUpdateTrace                                                                              │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ /home/wsluser/Work/alpaca-lora/generate.py:48 in main                                              │
│                                                                                                  │
│    45 │   │   │   torch_dtype=torch.float16,                                                     │
│    46 │   │   │   device_map="auto",                                                             │
│    47 │   │   )                                                                                  │
│ ❱  48 │   │   model = PeftModel.from_pretrained(                                                 │
│    49 │   │   │   model,                                                                         │
│    50 │   │   │   lora_weights,                                                                  │
│    51 │   │   │   torch_dtype=torch.float16,                                                     │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/peft/peft_model.py:145 in         │
│ from_pretrained                                                                                  │
│                                                                                                  │
│    142 │   │   if config.task_type not in MODEL_TYPE_TO_PEFT_MODEL_MAPPING.keys():               │
│    143 │   │   │   model = cls(model, config)                                                    │
│    144 │   │   else:                                                                             │
│ ❱  145 │   │   │   model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config)     │
│    146 │   │                                                                                     │
│    147 │   │   # load weights if any                                                             │
│    148 │   │   if os.path.exists(os.path.join(model_id, WEIGHTS_NAME)):                          │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/peft/peft_model.py:560 in         │
│ __init__                                                                                         │
│                                                                                                  │
│    557 │   """                                                                                   │
│    558 │                                                                                         │
│    559 │   def __init__(self, model, peft_config: PeftConfig):                                   │
│ ❱  560 │   │   super().__init__(model, peft_config)                                              │
│    561 │   │   self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_f  │
│    562 │                                                                                         │
│    563 │   def forward(                                                                          │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/peft/peft_model.py:79 in __init__ │
│                                                                                                  │
│     76 │   │   if isinstance(self.peft_config, PromptLearningConfig):                            │
│     77 │   │   │   self._setup_prompt_encoder()                                                  │
│     78 │   │   else:                                                                             │
│ ❱   79 │   │   │   self.base_model = LoraModel(peft_config, model)                               │
│     80 │   │   if getattr(self.peft_config, "modules_to_save", None) is not None:                │
│     81 │   │   │   self.modules_to_save = self.peft_config.modules_to_save                       │
│     82 │   │   │   _set_trainable(self)                                                          │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/peft/tuners/lora.py:133 in        │
│ __init__                                                                                         │
│                                                                                                  │
│   130 │   │   super().__init__()                                                                 │
│   131 │   │   self.peft_config = config                                                          │
│   132 │   │   self.model = model                                                                 │
│ ❱ 133 │   │   self._find_and_replace()                                                           │
│   134 │   │   mark_only_lora_as_trainable(self.model, self.peft_config.bias)                     │
│   135 │   │   self.forward = self.model.forward                                                  │
│   136                                                                                            │
│                                                                                                  │
│ /home/wsluser/.pyenv/versions/3.8.16/lib/python3.8/site-packages/peft/tuners/lora.py:170 in        │
│ _find_and_replace                                                                                │
│                                                                                                  │
│   167 │   │   │   │   │   kwargs.update(                                                         │
│   168 │   │   │   │   │   │   {                                                                  │
│   169 │   │   │   │   │   │   │   "has_fp16_weights": target.state.has_fp16_weights,             │
│ ❱ 170 │   │   │   │   │   │   │   "memory_efficient_backward": target.state.memory_efficient_b   │
│   171 │   │   │   │   │   │   │   "threshold": target.state.threshold,                           │
│   172 │   │   │   │   │   │   │   "index": target.index,                                         │
│   173 │   │   │   │   │   │   }                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'MatmulLtState' object has no attribute 'memory_efficient_backward'
```

**Comment by JulesGM** [comment]
this issue should be in `peft`

**Comment by JulesGM** [comment]
I'm getting the same thing for `google/flan-t5-*`

**Comment by chrisociepa** [comment]
I am not sure if this is the same problem but with the same versions of pip packages, CUDA 12.1 and RTX 4090 I see the following logs:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "~/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "~/.local/lib/python3.8/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "~/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "~/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "~/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "~/.local/lib/python3.8/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "~/.local/lib/python3.8/site-packages/gradio/interface.py", line 621, in fn
    for output in self.fn(*args):
  File "generate.py", line 150, in evaluate
    generation_output = model.generate(
  File "~/.local/lib/python3.8/site-packages/peft/peft_model.py", line 627, in generate
    outputs = self.base_model.generate(**kwargs)
  File "~/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 1524, in generate
    return self.beam_search(
  File "~/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 2810, in beam_search
    outputs = self(
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/peft/tuners/lora.py", line 591, in forward
    result = super().forward(x)
  File "~/.local/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "~/.local/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "~/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "~/.local/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 317, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "~/.local/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1698, in transform
    prev_device = pre_call(A.device)
AttributeError: 'NoneType' object has no attribute 'device'
```
It occures when I try generating a response with `generate.py` script (command: `python3 generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'`). I tried an older PEFT version (`0.2.0`) but see the same error. Does anyone see such error?

**Comment by bobgar** [comment]
I solved this with pip install bitsandbytes==0.37.2  hopefully that works for you guys too!

**Comment by lixianwa** [comment]
> I solved this too! thanks!

**Comment by racerxdl** [comment]
With bitsandbytes==0.37.2 I got another error:

```
libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats
```

**Comment by chilljudaoren** [comment]
> With bitsandbytes==0.37.2 I got another error:
> 
> ```
> libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats
> ```

I solve this issue by copying cuda cp

**Comment by Narayan-21** [comment]
bitsandbytes=0.44.0 , accelerate=1.1.1, peft= 0.14.0, transformers=4.46.3 and torch=2.5.1 worked for me

**Comment by chilljudaoren** [comment]
thanks!

Narayan Jangid ***@***.***> 于2025年1月21日周二 02:35写道：

**Comment by skl519** [comment]
transformers==4.48.0  => transformers==4.28.0

**Comment by coder1165** [comment]
> bitsandbytes=0.44.0 , accelerate=1.1.1, peft= 0.14.0, transformers=4.46.3 and torch=2.5.1 worked for me

Worked for me too!  But when i trying import "prepare_model_for_int8_training" from peft, report error "cannot import name 'prepare_model_for_int8_training' from 'peft'", I fixed it by change it to "prepare_model_for_kbit_training ".

**Comment by zXshinidie** [comment]
pip install bitsandbytes==0.43.3 triton==2.3.0
