### ISSUE TITLE
IndexError: piece id is out of range.

### ISSUE THREAD

**Issue by ChrisXULC** [tloen/alpaca-lora#286]
Traceback (most recent call last):
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/gradio/blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/gradio/blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/gradio/interface.py", line 641, in fn
    for output in self.fn(*args):
  File "/root/LMFlow/cn_llama/packages/alpaca-lora-main/generate.py", line 143, in evaluate
    decoded_output = tokenizer.decode(output)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3485, in decode
    return self._decode(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 129, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by ElleLeonne** [comment]
Are you just running this out of the box with no modifications?

Which llama? Which transformers version?

**Comment by ChrisXULC** [comment]
> 
yes. base model is llama-7b, and the version of transformers is 4.28 dev.

**Comment by ElleLeonne** [comment]
I edited my previous reply with updated info

**Comment by ChrisXULC** [comment]
> 

I will try it. Thank you~
