### ISSUE TITLE
Is it possible to do inference (i.e. run generate.py) without a GPU?

### ISSUE THREAD

**Issue by georgihacker** [tloen/alpaca-lora#29]
Hi all,

I am trying to start generate.py, but don't have a CUDA card? (Actually I can insert an old Quadro K2000, if this helps?)
After all the steps in the setup section, I get the following:

```
/home/georgi/Documents/GitHub/alpaca-lora/venv/bin/python /home/georgi/Documents/GitHub/alpaca-lora/generate.py 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Traceback (most recent call last):
  File "/home/georgi/Documents/GitHub/alpaca-lora/generate.py", line 7, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2591, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
                        

Process finished with exit code 1

```
Is there a way around this? I tried inserting _load_in_8bit_fp32_cpu_offload=True_ in a few places, but doesn't fix it.

Thanks!

**Comment by lxe** [comment]
I think you might need deepspeed or accelerate for that.

**Comment by georgihacker** [comment]
Why do we need this step https://github.com/TimDettmers/bitsandbytes/blob/main/compile_from_source.md instead of just doing pip install?

**Comment by benob** [comment]
> Why do we need this step https://github.com/TimDettmers/bitsandbytes/blob/main/compile_from_source.md instead of just doing pip install?

it requires compiling a library which is not installed by pip

**Comment by georgihacker** [comment]
I inserted my old card and did some compiling, but still getting
`CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to compile it from source?
`

and 
```

RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```


Any ideas where the compiled library should be placed so that it is found correctly?
Thanks!

**Comment by georgihacker** [comment]
if it helps someone: the compiled lib needs to go in /home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/bitsandbytes

**Comment by ANMahmood** [comment]
> if it helps someone: the compiled lib needs to go in /home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/bitsandbytes

Hi, were you able to run it on CPU-only Windows machine?

**Comment by ANMahmood** [comment]
Is this thread resolved, it seems CPU only inference on Windows (especially on 4-bit) isn't working?

**Comment by ThatCoffeeGuy** [comment]
an easy workaround for now is just comment out


```#if torch.cuda.is_available():
#    device = "cuda"
#else:
#    device = "cpu"```

and add right below. : 
device = "cpu"

**Comment by georgihacker** [comment]
Where is this @ThatCoffeeGuy? In which file?

**Comment by georgihacker** [comment]
I reach this state:

```
Traceback (most recent call last):
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1059, in process_api
    result = await self.call_function(
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/gradio/blocks.py", line 868, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/georgi/Documents/GitHub/alpaca-lora/generate.py", line 61, in evaluate
    input_ids = inputs["input_ids"].cuda()
  File "/home/georgi/Documents/GitHub/alpaca-lora/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

```

**Comment by ThatCoffeeGuy** [comment]
> Where is this @ThatCoffeeGuy? In which file?

In generate.py

**Comment by eschibli** [comment]
Be cautious about running outside of 8-bit mode, I saw much worse results using the cpu-only version of bitsandbytes
