### ISSUE TITLE
Windows Error：AttributeError: function 'clion32bit_g32' not found

### ISSUE THREAD

**Issue by JOY-SWang** [tloen/alpaca-lora#356]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "D:\wjy-dialog\v2\alpaca-lora\finetune.py", line 16, in <module>
    from peft import (
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import AdaLoraModel, LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\optim\__init__.py", line 8, in <module>
    from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\optim\adagrad.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer1State
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\optim\optimizer.py", line 12, in <module>
    import bitsandbytes.functional as F
  File "C:\Anaconda3\envs\alpaca\lib\site-packages\bitsandbytes\functional.py", line 39, in <module>
    lib.clion32bit_g32,
  File "C:\Anaconda3\envs\alpaca\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Anaconda3\envs\alpaca\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'clion32bit_g32' not found

**Comment by JOY-SWang** [comment]
How to slove this bug?(AttributeError: function 'clion32bit_g32' not found)
