### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by assmdx** [tloen/alpaca-lora#368]
```
loading cached split indices for dataset at /Users/assmdx/.cache/huggingface/datasets/json/default-0d678e1ca93d5725/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e/cache-4146e0df6cc0afad.arrow and /Users/assmdx/.cache/huggingface/datasets/json/default-0d678e1ca93d5725/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e/cache-8e26b93b5e905d58.arrow
Traceback (most recent call last):
  File "/Users/assmdx/llma/ld/alpaca-lora/finetune.py", line 288, in <module>
    fire.Fire(train)
  File "/Users/assmdx/llma/ld/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/assmdx/llma/ld/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/assmdx/llma/ld/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/assmdx/llma/ld/alpaca-lora/finetune.py", line 236, in train
    trainer = transformers.Trainer(
  File "/Users/assmdx/llma/ld/lib/python3.10/site-packages/transformers/trainer.py", line 498, in __init__
    self._move_model_to_device(model, args.device)
  File "/Users/assmdx/llma/ld/lib/python3.10/site-packages/transformers/trainer.py", line 740, in _move_model_to_device
    model = model.to(device)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by assmdx** [comment]
finetune.py:
```
import os
import sys
from typing import List

import fire
import torch
import transformers
from datasets import load_dataset

"""
Unused imports:
import torch.nn as nn
import bitsandbytes as bnb
"""

from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
    prepare_model_for_int8_training,
    set_peft_model_state_dict,
)
from transformers import LlamaForCausalLM, LlamaTokenizer, BitsAndBytesConfig

from utils.prompter import Prompter

quantization_config = BitsAndBytesConfig(llm_int8_enable_fp32_cpu_offload=True)

def train(
    # model/data params
    base_model: str = "",  # the only required argument
    data_path: str = "yahma/alpaca-cleaned",
    output_dir: str = "./lora-alpaca",
    # training hyperparams
    batch_size: int = 128,
    micro_batch_size: int = 4,
    num_epochs: int = 3,
    learning_rate: float = 3e-4,
    cutoff_len: int = 256,
    val_set_size: int = 2000,
    # lora hyperparams
    lora_r: int = 8,
    lora_alpha: int = 16,
    lora_dropout: float = 0.05,
    lora_target_modules: List[str] = [
        "q_proj",
        "v_proj",
    ],
    # llm hyperparams
    train_on_inputs: bool = True,  # if False, masks out inputs in loss
    add_eos_token: bool = False,
    group_by_length: bool = False,  # faster, but produces an odd training loss curve
    # wandb params
    wandb_project: str = "",
    wandb_run_name: str = "",
    wandb_watch: str = "",  # options: false | gradients | all
    wandb_log_model: str = "",  # options: false | true
    resume_from_checkpoint: str = None,  # either training checkpoint or final adapter
    prompt_template_name: str = "alpaca",  # The prompt template to use, will default to alpaca.
):
    if int(os.environ.get("LOCAL_RANK", 0)) == 0:
        print(
            f"Training Alpaca-LoRA model with params:\n"
            f"base_model: {base_model}\n"
            f"data_path: {data_path}\n"
            f"output_dir: {output_dir}\n"
            f"batch_size: {batch_size}\n"
            f"micro_batch_size: {micro_batch_size}\n"
            f"num_epochs: {num_epochs}\n"
            f"learning_rate: {learning_rate}\n"
            f"cutoff_len: {cutoff_len}\n"
            f"val_set_size: {val_set_size}\n"
            f"lora_r: {lora_r}\n"
            f"lora_alpha: {lora_alpha}\n"
            f"lora_dropout: {lora_dropout}\n"
            f"lora_target_modules: {lora_target_modules}\n"
            f"train_on_inputs: {train_on_inputs}\n"
            f"add_eos_token: {add_eos_token}\n"
            f"group_by_length: {group_by_length}\n"
            f"wandb_project: {wandb_project}\n"
            f"wandb_run_name: {wandb_run_name}\n"
            f"wandb_watch: {wandb_watch}\n"
            f"wandb_log_model: {wandb_log_model}\n"
            f"resume_from_checkpoint: {resume_from_checkpoint or False}\n"
            f"prompt template: {prompt_template_name}\n"
        )
    assert (
        base_model
    ), "Please specify a --base_model, e.g. --base_model='huggyllama/llama-7b'"
    gradient_accumulation_steps = batch_size // micro_batch_size

    prompter = Prompter(prompt_template_name)

    device_map = "auto"
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    ddp = world_size != 1
    if ddp:
        device_map = {"": int(os.environ.get("LOCAL_RANK") or 0)}
        gradient_accumulation_steps = gradient_accumulation_steps // world_size

    # Check if parameter passed or if set within environ
    use_wandb = len(wandb_project) > 0 or (
        "WANDB_PROJECT" in os.environ and len(os.environ["WANDB_PROJECT"]) > 0
    )
    # Only overwrite environ if wandb param passed
    if len(wandb_project) > 0:
        os.environ["WANDB_PROJECT"] = wandb_project
    if len(wandb_watch) > 0:
        os.environ["WANDB_WATCH"] = wandb_watch
    if len(wandb_log_model) > 0:
        os.environ["WANDB_LOG_MODEL"] = wandb_log_model

    model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=True,
        # torch_dtype=torch.float16,
        torch_dtype=torch.float32,
        offload_folder='./offload_folder',
        device_map=device_map,
        quantization_config=quantization_config,
    )

    tokenizer = LlamaTokenizer.from_pretrained(base_model)

    tokenizer.pad_token_id = (
        0  # unk. we want this to be different from the eos token
    )
    tokenizer.padding_side = "left"  # Allow batched inference

    def tokenize(prompt, add_eos_token=True):
        # there's probably a way to do this with the tokenizer settings
        # but again, gotta move fast
        result = tokenizer(
            prompt,
            truncation=True,
            max_length=cutoff_len,
            padding=False,
            return_tensors=None,
        )
        if (
            result["input_ids"][-1] != tokenizer.eos_token_id
            and len(result["input_ids"]) < cutoff_len
            and add_eos_token
        ):
            result["input_ids"].append(tokenizer.eos_token_id)
            result["attention_mask"].append(1)

        result["labels"] = result["input_ids"].copy()

        return result

    def generate_and_tokenize_prompt(data_point):
        full_prompt = prompter.generate_prompt(
            data_point["instruction"],
            data_point["input"],
            data_point["output"],
        )
        tokenized_full_prompt = tokenize(full_prompt)
        if not train_on_inputs:
            user_prompt = prompter.generate_prompt(
                data_point["instruction"], data_point["input"]
            )
            tokenized_user_prompt = tokenize(
                user_prompt, add_eos_token=add_eos_token
            )
            user_prompt_len = len(tokenized_user_prompt["input_ids"])

            if add_eos_token:
                user_prompt_len -= 1

            tokenized_full_prompt["labels"] = [
                -100
            ] * user_prompt_len + tokenized_full_prompt["labels"][
                user_prompt_len:
            ]  # could be sped up, probably
        return tokenized_full_prompt

    model = prepare_model_for_int8_training(model)

    config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=lora_target_modules,
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, config)

    if data_path.endswith(".json") or data_path.endswith(".jsonl"):
        data = load_dataset("json", data_files=data_path)
    else:
        data = load_dataset(data_path)

    if resume_from_checkpoint:
        # Check the available weights and load them
        checkpoint_name = os.path.join(
            resume_from_checkpoint, "pytorch_model.bin"
        )  # Full checkpoint
        if not os.path.exists(checkpoint_name):
            checkpoint_name = os.path.join(
                resume_from_checkpoint, "adapter_model.bin"
            )  # only LoRA model - LoRA config above has to fit
            resume_from_checkpoint = (
                False  # So the trainer won't try loading its state
            )
        # The two files above have a different name depending on how they were saved, but are actually the same.
        if os.path.exists(checkpoint_name):
            print(f"Restarting from {checkpoint_name}")
            adapters_weights = torch.load(checkpoint_name)
            set_peft_model_state_dict(model, adapters_weights)
        else:
            print(f"Checkpoint {checkpoint_name} not found")

    model.print_trainable_parameters()  # Be more transparent about the % of trainable params.

    if val_set_size > 0:
        train_val = data["train"].train_test_split(
            test_size=val_set_size, shuffle=True, seed=42
        )
        train_data = (
            train_val["train"].shuffle().map(generate_and_tokenize_prompt)
        )
        val_data = (
            train_val["test"].shuffle().map(generate_and_tokenize_prompt)
        )
    else:
        train_data = data["train"].shuffle().map(generate_and_tokenize_prompt)
        val_data = None

    if not ddp and torch.cuda.device_count() > 1:
        # keeps Trainer from trying its own DataParallelism when more than 1 gpu is available
        model.is_parallelizable = True
        model.model_parallel = True

    trainer = transformers.Trainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=val_data,
        args=transformers.TrainingArguments(
            per_device_train_batch_size=micro_batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            warmup_steps=100,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            # fp16=True,
            fp16=False,
            logging_steps=10,
            optim="adamw_torch",
            evaluation_strategy="steps" if val_set_size > 0 else "no",
            save_strategy="steps",
            eval_steps=200 if val_set_size > 0 else None,
            save_steps=200,
            output_dir=output_dir,
            save_total_limit=3,
            load_best_model_at_end=True if val_set_size > 0 else False,
            ddp_find_unused_parameters=False if ddp else None,
            group_by_length=group_by_length,
            report_to="wandb" if use_wandb else None,
            run_name=wandb_run_name if use_wandb else None,
        ),
        data_collator=transformers.DataCollatorForSeq2Seq(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        ),
    )
    model.config.use_cache = False

    old_state_dict = model.state_dict
    model.state_dict = (
        lambda self, *_, **__: get_peft_model_state_dict(
            self, old_state_dict()
        )
    ).__get__(model, type(model))

    if torch.__version__ >= "2" and sys.platform != "win32":
        model = torch.compile(model)

    trainer.train(resume_from_checkpoint=resume_from_checkpoint)

    model.save_pretrained(output_dir)

    print(
        "\n If there's a warning about missing keys above, please disregard :)"
    )


if __name__ == "__main__":
    fire.Fire(train)

```

**Comment by QDxiaoye** [comment]
I had the same problem

**Comment by lywinged** [comment]
It means torch_dtype=torch.float32 doesn't work

**Comment by assmdx** [comment]
> It means torch_dtype=torch.float32 doesn't work
is there any way to solve this?

**Comment by lywinged** [comment]
> It means torch_dtype=torch.float32 doesn't work
> is there any way to solve this?

I didn’t find the solution yet, using fp16 now.

**Comment by renmengjie7** [comment]
When I try to transfer the model from cuda to cpu, I encountered the same problem.
my code is
```python
self.base_model = LlamaForCausalLM.from_pretrained(
            self.base_model_dir,
            load_in_8bit=self.load_8bit,
            torch_dtype=torch.float16,
            device_map="auto",
        )
self.model = PeftModel.from_pretrained(
            self.base_model,
            self.lora_weights_dir,
            torch_dtype=torch.float16,
        )
self.model.to('cpu')
self.base_model.to('cpu')
```

**Comment by assmdx** [comment]
> > It means torch_dtype=torch.float32 doesn't work
> > is there any way to solve this?
> 
> I didn’t find the solution yet, using fp16 now.

we must need a GPU to run fine-tune.py?  if use torch.float16， i got another error: https://stackoverflow.com/questions/73530569/pytorch-matmul-runtimeerror-addmm-impl-cpu-not-implemented-for-half

**Comment by gabgiani** [comment]
Some news with this problem? I have the same error .. I analysed the memory use and I have 60% of memory in use when occurs the error. Someone know the cause of this error?

**Comment by assmdx** [comment]
I solved this problem by using RTX 3090(24GB) * 1 + 43GB Memory + 12 vCPU Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz。May be we should use better GPU  and memory to run this project，

**Comment by flak1990** [comment]
> I solved this problem by using RTX 3090(24GB) * 1 + 43GB Memory + 12 vCPU Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz。May be we should use better GPU and memory to run this project，

What's your cuda version and torch version? I'm wondering whether this makes the problem.

**Comment by wemoveon2** [comment]
> It means torch_dtype=torch.float32 doesn't work

@lywinged do you know why that is the case?

**Comment by wemoveon2** [comment]
> > It means torch_dtype=torch.float32 doesn't work
> > is there any way to solve this?
> 
> I didn’t find the solution yet, using fp16 now.

I think this might've worked because you are no longer offloading to CPU/disk as your weights fit into GPU memory, can you confirm @lywinged?

**Comment by wrmthorne** [comment]
I had this issue for a long time while trying to load llama-13b in 8bit. Even though I had the space to fit the model onto my 3090 in 8bit, `device_map="auto"` was still offloading to cpu. I set the device map manually on both the base model and the peft model:
```python
base_model = AutoModelForCausalLM.from_pretrained(
    peft_config.base_model_name_or_path,
    return_dict=True,
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map={'': 0},
)

model = PeftModel.from_pretrained(base_model, args.lora_weights, device_map={'': 0})
```

I used `model.hf_device_map` to inspect the device that each layer was on. I can't comment on why offloading causes this issue but putting it on the same device seems to solve it at least.

**Comment by lichen914** [comment]
maybe peftmodle has the bug，i use 
`    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, inference_mode=True,
        r=8,
        lora_alpha=32, lora_dropout=0.1)
    model = get_peft_model(model, peft_config)

    lora_w = torch.load(lora_weights)
    model.load_state_dict(lora_w, strict=False)`  fix it

i use llama model，find layer behind 25 is all meta tensor

**Comment by chintanckg** [comment]
+1
Facing the same issue.

**Comment by littlefatfat** [comment]
+1
Facing the same issue.

**Comment by mtisz** [comment]
Same here

**Comment by ycjcl868** [comment]
Same here

**Comment by vi-pak** [comment]
I faced the same issue when moving from GPU to CPU instance which is doing the processing. In my case **removing** those two parameters did the trick:
device_map = 'auto', offload_folder="offload".

**Comment by wemoveon2** [comment]
From an associated issue in another repo: 
>When loading the model using device_map="auto" on a GPU with insufficient VRAM, Transformers tries to offload the rest of the model onto the CPU/disk. The problem is, the model is being loaded in float16 which is not supported by CPU/disk (neither is 8-bit). So, torch offloads the model as a meta-tensor (no data). In other words, parts of the model are missing.
>
> Solutions:
>
> Using the -g and -r arguments: gives Accelerate a manual config for where it should offload the model. Accelerate takes care of the dtype.
> Loading the model using either float32 or bfloat16 should work. Note, I haven't tested this one out myself but it should work.
> Using a larger GPU. This prevents offloading in the first place.

ref
https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1518319626
https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1537234491

**Comment by lxycopper** [comment]
For reference, I once meet similar problem, that is because I set one layer of the model to be loaded on CUDA device independently, when I remove the loading, it works.
![image](https://github.com/tloen/alpaca-lora/assets/52530394/10f436d4-a0ba-4d64-963f-4f99dc97559f)

**Comment by tszslovewanpu** [comment]
more GPUs is ok

**Comment by 18207809132** [comment]
"device_map": "auto" change to "device_map": "cuda", and more GPUs
