### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by wpy-hd** [tloen/alpaca-lora#377]
When I run 'generate.py' ,  I meet the following error:
"""
Traceback (most recent call last):
  File "/home/dell/wpy/sgpt/alpaca/alpaca-lora/generate_without_gr.py", line 204, in <module>
    fire.Fire(main)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/fire/core.py", line 480, in _Fire
    target=component.__name__)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/dell/wpy/sgpt/alpaca/alpaca-lora/generate_without_gr.py", line 193, in main
    for i in response:
  File "/home/dell/wpy/sgpt/alpaca/alpaca-lora/generate_without_gr.py", line 166, in evaluate
    max_new_tokens=max_new_tokens,
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/peft/peft_model.py", line 580, in generate
    return self.base_model.generate(**kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/wpy/sgpt/transformers/src/transformers/generation/utils.py", line 1534, in generate
    **model_kwargs,
  File "/home/dell/wpy/sgpt/transformers/src/transformers/generation/utils.py", line 2814, in beam_search
    output_hidden_states=output_hidden_states,
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dell/wpy/sgpt/transformers/src/transformers/models/llama/modeling_llama.py", line 696, in forward
    return_dict=return_dict,
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/wpy/sgpt/transformers/src/transformers/models/llama/modeling_llama.py", line 583, in forward
    use_cache=use_cache,
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dell/wpy/sgpt/transformers/src/transformers/models/llama/modeling_llama.py", line 298, in forward
    use_cache=use_cache,
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dell/wpy/sgpt/transformers/src/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/peft/tuners/lora.py", line 502, in forward
    result = super().forward(x)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/bitsandbytes/autograd/_functions.py", line 337, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "/home/dell/.conda/envs/focus_env/lib/python3.7/site-packages/bitsandbytes/functional.py", line 1724, in transform
    prev_device = pre_call(A.device)
AttributeError: 'NoneType' object has no attribute 'device'
""'
The instruction is "Tell me about alpacas." and  I print its input vector:
"""
{'input_ids': tensor([[    0, 13866,   338,   385, 15278,   393, 16612,   263,  3414, 29889,
         14350,   263,  2933,   393,  7128,  2486,  1614,  2167,   278,  2009,
         29889,    13,    13,  2277, 29937,  2799,  4080, 29901,    13, 29911,
           514,   592,  1048,   394, 29886,   562,   294, 29889,    13,    13,
          2277, 29937, 13291, 29901,    13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
"""
I don't know what causes the error.

**Comment by wpy-hd** [comment]
I find the solution : https://github.com/tloen/alpaca-lora/issues/21
