### ISSUE TITLE
DDP - "...got multiple values for keyword argument 'backend'"

### ISSUE THREAD

**Issue by getorca** [tloen/alpaca-lora#409]
I'm trying to run DDP on 5 3090s. I'm running `OMP_NUM_THREADS=4 WORLD_SIZE=5 torchrun --nproc_per_node=5 --master_port=1234 finetune.py` I'm getting the following error:

'''
Map:  81%|█████████████████████████████████████████████████████████████████████████████████████████▋                     | 1615/2000 [00:03<00:00, 513.09 examples/s]Traceback (most recent call last):
  File "/home/llmadmin/alpaca-lora/finetune.py", line 290, in <module>
    fire.Fire(train)
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llmadmin/alpaca-lora/finetune.py", line 243, in train
    args=transformers.TrainingArguments(
  File "<string>", line 110, in __init__
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/transformers/training_args.py", line 1263, in __post_init__
    and (self.device.type != "cuda")
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/transformers/training_args.py", line 1627, in device
    return self._setup_devices
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/transformers/training_args.py", line 1561, in _setup_devices
    self.distributed_state = PartialState(backend=self.xpu_backend)
  File "/home/llmadmin/anaconda3/envs/lora-trainer/lib/python3.10/site-packages/accelerate/state.py", line 129, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
TypeError: torch.distributed.distributed_c10d.init_process_group() got multiple values for keyword argument 'backend'

'''

Additional details: 
- line 243 for me is `args=transformers.TrainingArguments(`
- it appears MP is working fine.

**Comment by getorca** [comment]
Fun...It was dependency hell... 

as per https://github.com/lm-sys/FastChat/issues/485, downgrading to `transformers==4.28.1` resolved the issue. But I'm sure it breaks running in some other config, lol

**Comment by teknium1** [comment]
Why cant HF get their stuff together lmao wasting my money with their issues
