### ISSUE TITLE
Unable to run the docker image due to - Python.h: No such file or directory

### ISSUE THREAD

**Issue by armsp** [tloen/alpaca-lora#431]
I just cloned the repo and built the image which was a success. But running it doesn't work.
While using docker on WSL2 ...this is the final output - 
```bash
❯ docker run --gpus=all --shm-size 64g -p 7860:7860 -v ${HOME}/.cache:/root/.cache --rm alpaca-lora generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/tmp/tmpzgz3av6b/main.c:3:10: fatal error: Python.h: No such file or directory
    3 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Traceback (most recent call last):
  File "/workspace/generate.py", line 8, in <module>
    from peft import PeftModel
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import (
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/usr/local/lib/python3.10/dist-packages/triton/__init__.py", line 12, in <module>
    from .runtime import (
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/__init__.py", line 3, in <module>
    from .driver import driver
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 153, in <module>
    driver = create_driver()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 148, in create_driver
    return CudaDriver()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 71, in __init__
    self.utils = CudaUtils()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 46, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 82, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpzgz3av6b/main.c', '-O3', '-I/usr/local/lib/python3.10/dist-packages/triton/common/../third_party/cuda/include', '-I/usr/include/python3.10', '-I/tmp/tmpzgz3av6b', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpzgz3av6b/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/usr/lib/x86_64-linux-gnu']' returned non-zero exit status 1.
```
I get the same issue with the docker compose file.
I tried it on Windows natively too, but that also errors - 
```bash
>  docker run --gpus=all --shm-size 64g -p 7860:7860 -v ${HOME}/.cache:/root/.cache --rm alpaca-lora-win generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
100%|██████████| 39/39 [00:08<00:00,  4.87it/s]
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/tmp/tmptzfkkzip/main.c:3:10: fatal error: Python.h: No such file or directory
    3 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/workspace/generate.py", line 8, in <module>
    from peft import PeftModel
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 31, in <module>

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
    from .tuners import (
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/usr/local/lib/python3.10/dist-packages/triton/__init__.py", line 12, in <module>
    from .runtime import (
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/__init__.py", line 3, in <module>
    from .driver import driver
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 153, in <module>
    driver = create_driver()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 148, in create_driver
    return CudaDriver()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 71, in __init__
    self.utils = CudaUtils()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 46, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 82, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmptzfkkzip/main.c', '-O3', '-I/usr/local/lib/python3.10/dist-packages/triton/common/../third_party/cuda/include', '-I/usr/include/python3.10', '-I/tmp/tmptzfkkzip', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmptzfkkzip/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/usr/lib/x86_64-linux-gnu']' returned non-zero exit status 1.
```
Any idea how to get it working? I am running this on a laptop with 6GB VRAM and 24GB RAM.

**Comment by kpuri06** [comment]
It seems like the main issue here is related to the missing Python header files. The error message "fatal error: Python.h: No such file or directory" indicates that the required header files are not found in the expected locations.

To fix this issue, you need to install the Python development package, which includes the header files. Since you are using Python 3.10, you can install the development package with the following command:

arduino
Copy code
sudo apt-get install python3.10-dev
After installing the Python development package, you can try running the Docker command again.

If you still encounter issues, you can try the following steps:

Make sure your NVIDIA drivers, CUDA toolkit, and cuDNN library are up-to-date and compatible with each other. You can follow the official NVIDIA installation guides for each component.

Verify that your GPU is detected and working correctly with the nvidia-smi command.

Check if the Docker container has access to the GPU by running a simple GPU-enabled Docker image, such as nvidia/cuda:11.0-base. You can try running the following command to test the GPU access:

css
Copy code
docker run --gpus=all --rm nvidia/cuda:11.0-base nvidia-smi
Ensure that your Docker installation has the nvidia-container-toolkit package installed. You can install it with the following commands:
bash
Copy code
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install -y nvidia-docker2
After performing these steps, restart the Docker daemon and try running the command again. If you still face issues, please provide more details about your system configuration, such as the output of nvidia-smi, the installed NVIDIA driver version, and the installed CUDA toolkit version.

**Comment by CodiTrixta** [comment]
Running the command `sudo apt-get install python3.10-dev` didnt work for me but this did:

```
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10-dev
```

**Comment by evelynoliv** [comment]
I'm having the same problem on windows 11, here's my setup:
- wsl 2
- python 3.10
- cudatoolkit 11.3
- cudnn 8.1
- cuda 11.8

```
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/tmp/tmpczk65fng/main.c:3:10: fatal error: Python.h: No such file or directory
    3 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/workspace/generate.py", line 8, in <module>
    from peft import PeftModel
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import (
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/usr/local/lib/python3.10/dist-packages/triton/__init__.py", line 12, in <module>
    from .runtime import (
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/__init__.py", line 3, in <module>
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 82, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpczk65fng/main.c', '-O3', '-I/usr/local/lib/python3.10/dist-packages/triton/common/../third_party/cuda/include', '-I/usr/include/python3.10', '-I/tmp/tmpczk65fng', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpczk65fng/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/usr/lib/x86_64-linux-gnu']' returned non-zero exit status 1.

```

**Comment by armsp** [comment]
installing python dev does make the error go away ... but then the issue of VRAM creeps in...
