### ISSUE TITLE
RuntimeError: MPS does not support cumsum op with int64 input

### ISSUE THREAD

**Issue by ulshv** [tloen/alpaca-lora#449]
Error when running with basic example on MBP M1 Pro and sending prompt trough UI:
```
python3.10 generate.py \
    --load_8bit \
    --base_model 'decapoda-research/llama-7b-hf' \
    --lora_weights 'tloen/alpaca-lora-7b
```

Logs:

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/transformers/generation/utils.py:719: UserWarning: MPS: no support for int64 repeats mask, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Repeat.mm:236.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Traceback (most recent call last):
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/interface.py", line 632, in fn
    async for output in iterator:
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/Users/sergey/ai/alpaca-lora/generate.py", line 151, in evaluate
    generation_output = model.generate(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/peft/peft_model.py", line 739, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1604, in generate
    return self.beam_search(
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2900, in beam_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/sergey/ai/alpaca-lora/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 737, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input

**Comment by caballerofelipe** [comment]
Yep. Happens to me too. Same silicon.

**Comment by arpieb** [comment]
Same error on Intel MBP 16-in 2019 w 32GB running Ventura 13.4

**Comment by EnzoDeg40** [comment]
I found the solution on the pytorch forum. A nightly version of PyTorch solves the problem

```bash
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

Source : https://discuss.pytorch.org/t/mps-device-torch-backend/188412/2
