### ISSUE TITLE
Loading a quantized checkpoint into non-quantized Linear8bitLt is not supported.

### ISSUE THREAD

**Issue by mmealman** [tloen/alpaca-lora#457]
I'm curious as to why I'd be getting the below error on a train when it reaches 100% and tries the final save. For my system I'm Ubuntu 22 running two 3090's. 

A few relevant lib versions:

cuda-runtime              11.7.1                        0    nvidia
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
peft                      0.4.0.dev0               pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
transformers              4.29.1                   pypi_0    pypi

For my base model, I'm using https://huggingface.co/Neko-Institute-of-Science/LLaMA-7B-HF

I do have my finetune.py patched to handle a save issue with the newer peft:

    #old_state_dict = model.state_dict
    #model.state_dict = (
    #    lambda self, *_, **__: get_peft_model_state_dict(
    #        self, old_state_dict()
    #    )
    #).__get__(model, type(model))

But this code/environment/model has worked fine on trains before. Though in this case I'm training a much larger data set.

Traceback (most recent call last):
  File "/home/mmealman/src/alpaca-lora/finetune-crit-role.py", line 285, in <module>
    fire.Fire(train)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/mmealman/src/alpaca-lora/finetune-crit-role.py", line 275, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/transformers/trainer.py", line 2062, in _inner_training_loop
    self._load_best_model()
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/transformers/trainer.py", line 2238, in _load_best_model
    load_result = model.load_state_dict(state_dict, False)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 4 more times]
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2009, in load
    module._load_from_state_dict(
  File "/home/mmealman/miniconda3/envs/lora-training/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 298, in _load_from_state_dict
    raise RuntimeError("Loading a quantized checkpoint into non-quantized Linear8bitLt is "
RuntimeError: Loading a quantized checkpoint into non-quantized Linear8bitLt is not supported. Please call module.cuda() before module.load_state_dict()

**Comment by getorca** [comment]
which bitsandbytes?

But yes, I also just ran into this issue on 3090s, doesn't seem to be related to dataset size. Also with the newer packages you've listed.

Anyways here's my list of older packages (tested to be working without the above error from bnb):
```
bitsandbytes             0.37.2
transformers             4.28.1
peft                     0.3.0.dev0
```

These are the dependencies which seems to cause odd issues. 

here's the exact line in bitsandbytes throwing the runtime error: https://github.com/TimDettmers/bitsandbytes/blob/9e7cdc9ea95e9756d9f5621a0e2c7e2538363fae/bitsandbytes/nn/modules.py#LL298C41-L299C114

I can confirm those older package releases listed above work. Trying to sort out the issue with the newer bitsandbytes https://github.com/TimDettmers/bitsandbytes/issues/411

**Comment by dkqkxx** [comment]
transformers bugs, load_best_model_at_end should load_in_8bit

**Comment by getorca** [comment]
> transformers bugs, load_best_model_at_end should load_in_8bit

Do you have some additional context?

**Comment by dkqkxx** [comment]
> > transformers bugs, load_best_model_at_end should load_in_8bit
> 
> Do you have some additional context?

Sorry, I made some mistakes,

**Comment by dkqkxx** [comment]
> > transformers bugs, load_best_model_at_end should load_in_8bit
> 
> Do you have some additional context?

Ref https://github.com/tloen/alpaca-lora/issues/457#issuecomment-1553505127

**Comment by dkqkxx** [comment]
> > transformers bugs, load_best_model_at_end should load_in_8bit
> 
> Do you have some additional context?

Ref https://github.com/huggingface/peft/issues/394

**Comment by mmealman** [comment]
Sorry for the delay in response. I can confirm that bitsandbytes 0.37.2 worked. I also switched transformers and peft to the suggested versions. Unfortunately while the model finished training and saved, it produced garbage output during inference. I'm going to mark that up to "things get messy downgrading lib versions in the middle of a train" and do a fresh install, updating the requirements.txt to these versions and see how things go.

But I'm no longer getting this error on the final save. Thanks for the help.

**Comment by ryzn0518** [comment]
> Sorry for the delay in response. I can confirm that bitsandbytes 0.37.2 worked. I also switched transformers and peft to the suggested versions. Unfortunately while the model finished training and saved, it produced garbage output during inference. I'm going to mark that up to "things get messy downgrading lib versions in the middle of a train" and do a fresh install, updating the requirements.txt to these versions and see how things go.
> 
> But I'm no longer getting this error on the final save. Thanks for the help.

@mmealman hi, can you share the stable version running on your machine work well? 
such as:
```
transformers
peft
bitsandbytes
```
I also meet the error, I had  try various combinations of versions, thanks a lot.
