### ISSUE TITLE
Error on docker run

### ISSUE THREAD

**Issue by hyochan** [tloen/alpaca-lora#476]
Hi! I am trying to run this awesome project.

However when I run
```
docker run --gpus=all --shm-size 64g -p 7860:7860 -v ${HOME}/.cache:/root/.cache --rm alpaca-lora generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'
```

I see the below error. May I get any clue?

```
Downloading shards: 100%|██████████| 33/33 [03:33<00:00,  6.48s/it]:07<00:00, 84.9MB/s] 
Traceback (most recent call last):
  File "/workspace/generate.py", line 218, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/generate.py", line 42, in main
    model = LlamaForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2722, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu       
                        for more details.
```

**Comment by Rob97** [comment]
You need to update the generate.py script to run on it cpu since you removed the gpu from the parameters. Here is a link:https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu

Unfortunately, I'm still struggling to get it to work. If anyone had a script that I can copy and use to get started that'd be fantastic.

**Comment by hyochan** [comment]
> You need to update the generate.py script to run on it cpu since you removed the gpu from the parameters. Here is a link:https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
> 
> Unfortunately, I'm still struggling to get it to work. If anyone had a script that I can copy and use to get started that'd be fantastic.

I've not removed the GPU from the parameter. Where do you see that in the command?
