### ISSUE TITLE
expected scalar type Half but found Float

### ISSUE THREAD

**Issue by theophilegervet** [tloen/alpaca-lora#485]
Hi,

Following fine-tuning instructions gives the following error:
```
Traceback (most recent call last):
  File "/private/home/theop123/alpaca-lora/finetune.py", line 283, in <module>
    fire.Fire(train)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/private/home/theop123/alpaca-lora/finetune.py", line 273, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/transformers/trainer.py", line 1696, in train

    return inner_training_loop(
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/transformers/trainer.py", line 1973, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/transformers/trainer.py", line 2797, in training_step
    self.scaler.scale(loss).backward()
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/private/home/theop123/miniconda3/envs/alpaca-lora/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 476, in backward
    grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
RuntimeError: expected scalar type Half but found Float
```

Any idea what causes this?

**Comment by Qualia-Li** [comment]
same issue here, anyone found a solution?

**Comment by theophilegervet** [comment]
Could this be due to `bitsandbytes` not working for V100 GPUs? https://github.com/TimDettmers/bitsandbytes/issues/240
The code runs fine on a `A100` but fails on a `V100`.

**Comment by itjuba** [comment]
same error over here

**Comment by HongleiGu** [comment]
Turning fp16 in finetuen.py Trainer.train() to False solved the problem, but also theoretically increased training time. Any idea to solve it when fp16 is True?

**Comment by hwany-j** [comment]
Any updates for running on V100?

**Comment by xllau** [comment]
I encounter this problem on V100 too, anyone solved this problem?

**Comment by xllau** [comment]
Maybe the problem is caused by V100. But I have solved it by adding "with torch.autocast("cuda"): " before trainer.train(***) in fineturne.py.

**Comment by Qualia-Li** [comment]
@xllau did you see issues with bitsandbytes as well ?

**Comment by hwany-j** [comment]
@xllau I also did it, but there is an issue of loss explosion (go to infinity). Did you check that the model trains well?

**Comment by xllau** [comment]
> @xllau I also did it, but there is an issue of loss explosion (go to infinity). Did you check that the model trains well?

I am training the model, it seems problem exits and I am debugging. I will keep update if solved.

**Comment by dlnlpchenliyu** [comment]
It occurs while training on V100.
Firstly, I try to add 'with torch.autocast("cuda"):' above 'trainer.train', the error won't occur, but the loss keeps 0 all the time.
Then, I try to set fp16=False, it works, but it's really slow.
Finally, I delete 'load_in_8bit=True,' and 'model = prepare_model_for_int8_training(model)', it works and the training speed is ok, while the GPU memory cost doubles.

**Comment by binga** [comment]
Anyone knows if this works fine on A10 GPUs?

**Comment by ParaNoth** [comment]
> It occurs while training on V100. Firstly, I try to add 'with torch.autocast("cuda"):' above 'trainer.train', the error won't occur, but the loss keeps 0 all the time. Then, I try to set fp16=False, it works, but it's really slow. Finally, I delete 'load_in_8bit=True,' and 'model = prepare_model_for_int8_training(model)', it works and the training speed is ok, while the GPU memory cost doubles.

> Could this be due to `bitsandbytes` not working for V100 GPUs? [TimDettmers/bitsandbytes#240](https://github.com/TimDettmers/bitsandbytes/issues/240) The code runs fine on a `A100` but fails on a `V100`.

I have the same issue when I finetune baichuan7B which has similar struct to llama7b using the same code. Then I check the gradient and the loss and find they become nan.  After using debug tools to check the output of each layer, I find out that nan is caused by overflow on fp16. This seems to be because V100 does not support bf16 so the fp=True using fp16 instead. A100 suppot bf16 so it will not cause overflow and it will work well.
