### ISSUE TITLE
Stream tokens output

### ISSUE THREAD

**Issue by marcoripa96** [tloen/alpaca-lora#51]
Is it possible to stream each token of the output as soon as it is generated by the model? I guess it depends on the hugging face transformers classes and methods. Any solution to this?

**Comment by baleksey** [comment]
Yeah, you can do that. You need to create LogitsWarper

```
from transformers import LogitsWarper
class CallbackLogitsWarper(LogitsWarper):
    def __init__(self, tokenizer, callback):
        self.tokenizer = tokenizer
        self.callback = callback
        self.res_tokens = []

    def __call__(self, input_ids: torch.Tensor, scores: torch.Tensor) -> torch.FloatTensor:
        self.res_tokens.append(input_ids[0][-1])
        result = self.tokenizer.decode(self.res_tokens).lstrip()
        self.callback(result) # return current generation already in words format back
        return scores
```

Then add **logits_processor** param to your mode.generate()

```
def callback(result):
    print(result)
     
generation_output = model.generate(
    input_ids=input_ids,
    generation_config=generation_config,
    return_dict_in_generate=True,
    output_scores=True,
    max_new_tokens=100,
    logits_processor=[CallbackLogitsWarper(tokenizer, callback)],
)
```

**Comment by marcoripa96** [comment]
Thanks for the fast replay! I tried but it doesn't seem those are the final tokens produced in the generation_output variable.

This is what I did:

```py
from transformers import LogitsWarper
import torch
class CallbackLogitsWarper(LogitsWarper):
    def __init__(self, tokenizer, callback):
        self.tokenizer = tokenizer
        self.callback = callback
        self.res_tokens = []

    def __call__(self, input_ids: torch.Tensor, scores: torch.Tensor) -> torch.FloatTensor:
        self.res_tokens.append(input_ids[0][-1])
        # result = self.tokenizer.decode(self.res_tokens).lstrip()
        result = self.tokenizer.decode(input_ids[0][-1])
        self.callback(result)
        return scores
```
```py
generation_config = GenerationConfig(
    temperature=0.1,
    top_p=0.75,
    num_beams=4,
)

def callback(result):
    sys.stdout.write(result)

def evaluate(instruction, input=None):
    prompt = generate_prompt(instruction, input)
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].cuda()
    generation_output = model.generate(
        input_ids=input_ids,
        generation_config=generation_config,
        return_dict_in_generate=True,
        output_scores=True,
        max_new_tokens=256,
        logits_processor=[CallbackLogitsWarper(tokenizer, callback)]
    )
    
    for s in generation_output.sequences:
        output = tokenizer.decode(s)
        print()
        print("Response:", output.split("### Response:")[1].strip())
```
And this is what is being produced by "streaming" each token compared to the final generation_output:

```
Instruction: Give me a random sentence
 : <0x0A> The sun was sh ining bright ly in the sky, casting a ating the low over the landscape. </s> <0x0A>
Response: The sun was shining brightly in the clear blue sky.
```

**Comment by baleksey** [comment]
In generate config remove  **num_beams** parameter at all (or set it to 1, I guess)

**Comment by marcoripa96** [comment]
It kinda works now, but still I don't get why I get partial tokens and I don't really have a way to know which tokens needs to be joined (ch icken in the example below). Additionally what's with the `:` and `<0x0A>` strings at the beginning of the generated sentence?

```
Instruction: Tell me a funny joke
Response obtained decoding one token at a time : <0x0A> Why did the ch icken cross the road? To get to the other side! </s>
Response obtained decoding all tokens together: Why did the chicken cross the road? To get to the other side!
```

**Comment by baleksey** [comment]
": and <0x0A>" - are the part of trained response (actually it's ":\n"). You can replace(":\n","") before print out so you won't see it. As for strange "ch icken" this is because (not sure 100%) different tokens combinations can produce different results by tokenizer.decode() and if you try to decode each token by it's own - you'll see that often. That's why in my example I decode the whole result and send it instead of separate tokens. In this way result will be stable and expected.

**Comment by mripacampus** [comment]
I see. The problem with decoding each time the whole sequence is that it’s really not optimal. Imagine a server streaming the response. Ideally you would send one token each time and a possibile client would concatenate the responses to form the complete output. 

I tried looking around and it seems there would be open issues for supporting streaming on the generare function for the HG transformers library. I guess for now I can use this.

**Comment by baleksey** [comment]
It's not optimal, agree. Using this hack on my local app/gui so don't really care for now.

Please, let us know if you find a way to stream it one at a time without those artifacts.

**Comment by maralski** [comment]
Look at the approach used in this [repo](https://github.com/THUDM/ChatGLM-6B). It is a different model but you may be able to replicate the streaming approach.

**Comment by canonhui** [comment]
When I used the code of @baleksey I got this error: 
> Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. 

Full traceback as following: 
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1202, in run_node
    return nnmodule(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1057, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1136, in dispatch
    args, kwargs = self.validate_and_convert_non_fake_tensors(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1290, in validate_and_convert_non_fake_tensors
    return tree_map_only(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/utils/_pytree.py", line 266, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/utils/_pytree.py", line 247, in inner
    return f(x)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1282, in validate
    raise Exception(
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.embedding.default(*(Parameter containing:
tensor([[ 9.8884e-05, -2.3329e-04,  5.8460e-04,  ..., -3.4237e-04,
          5.9724e-05, -1.1957e-04],
        [ 1.5289e-02, -1.2154e-02,  1.2512e-02,  ...,  1.3092e-02,
          7.2174e-03, -6.8045e-04],
        [ 1.7433e-03,  1.7633e-03, -1.4465e-02,  ..., -1.1444e-02,
         -1.2665e-02,  3.7289e-04],
        ...,
        [-9.0179e-03,  3.0807e-02, -1.6708e-02,  ..., -1.2680e-02,
          1.0437e-02,  4.2343e-03],
        [-1.1368e-02, -1.4801e-02, -3.5667e-03,  ...,  6.5308e-03,
         -2.2263e-02, -6.1455e-03],
        [-1.3992e-02,  1.6985e-03, -2.1469e-02,  ...,  1.3527e-02,
          2.8290e-02, -8.9111e-03]], device='cuda:0', dtype=torch.float16), FakeTensor(FakeTensor(..., device='meta', size=(1, 44), dtype=torch.int64), cuda:0), 0), **{}) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1155, in get_fake_value
    return wrap_fake_exception(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1156, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1209, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_module old_forward___self___base_model_forward___self___model_forward___self___embed_tokens(*(FakeTensor(FakeTensor(..., device='meta', size=(1, 44), dtype=torch.int64), cuda:0),), **{}):
Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.embedding.default(*(Parameter containing:
tensor([[ 9.8884e-05, -2.3329e-04,  5.8460e-04,  ..., -3.4237e-04,
          5.9724e-05, -1.1957e-04],
        [ 1.5289e-02, -1.2154e-02,  1.2512e-02,  ...,  1.3092e-02,
          7.2174e-03, -6.8045e-04],
        [ 1.7433e-03,  1.7633e-03, -1.4465e-02,  ..., -1.1444e-02,
         -1.2665e-02,  3.7289e-04],
        ...,
        [-9.0179e-03,  3.0807e-02, -1.6708e-02,  ..., -1.2680e-02,
          1.0437e-02,  4.2343e-03],
        [-1.1368e-02, -1.4801e-02, -3.5667e-03,  ...,  6.5308e-03,
         -2.2263e-02, -6.1455e-03],
        [-1.3992e-02,  1.6985e-03, -2.1469e-02,  ...,  1.3527e-02,
          2.8290e-02, -8.9111e-03]], device='cuda:0', dtype=torch.float16), FakeTensor(FakeTensor(..., device='meta', size=(1, 44), dtype=torch.int64), cuda:0), 0), **{}) 
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/alpaca/alpaca-lora/generate.py", line 189, in <module>
    print("Response:", generator.evaluate(instruction))
  File "/data/alpaca/alpaca-lora/generate.py", line 118, in evaluate
    for choice in self.model(prompt):
  File "/data/alpaca/alpaca-lora/model_streaming.py", line 64, in __call__
    for (
  File "/data/alpaca/alpaca-lora/model_streaming.py", line 235, in generate
    outputs = self._infer(
  File "/data/alpaca/alpaca-lora/model_streaming.py", line 116, in _infer
    return model_fn(**kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 118, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 406, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1840, in run
    super().run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1029, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 292, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 260, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 93, in call_function
    return tx.inline_user_function_return(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1997, in inline_call_
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1029, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 263, in call_function
    return tx.inline_user_function_return(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1997, in inline_call_
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1029, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 292, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 260, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 93, in call_function
    return tx.inline_user_function_return(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1997, in inline_call_
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1041, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 263, in call_function
    return tx.inline_user_function_return(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1997, in inline_call_
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1029, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 292, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 260, in call_function
    return super().call_function(tx, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 93, in call_function
    return tx.inline_user_function_return(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1997, in inline_call_
    tracer.run()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 992, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 232, in call_function
    return wrap_fx_proxy(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 865, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 900, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1176, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nano-gpt/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 568, in forward
    inputs_embeds = self.embed_tokens(input_ids)

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

any idea of the possible cause?

**Comment by canonhui** [comment]
can we yield the value of the variable `result` in `CallbackLogitsWarper.__call__` to a generator?

**Comment by mripacampus** [comment]
You can, I used a queue for that. Enqueue the result of the callback and infinitely loop and wait till there is a new item in the queue, then yield that item. I’ll give an example later on

**Comment by canonhui** [comment]
So in this way, we need multiprocessing to simultaneously run the generate and the yield?

**Comment by mripacampus** [comment]
Exactly! This is how I did it:

```python
def generate_streaming_completion(options):
  model = options.pop("model")
  tokenizer = options.pop("tokenizer")
  model_options = options.pop("model_options")
  stream = model_options.stream and model_options.num_beams == 1

  q = Queue()

  generation_config = GenerationConfig(
    temperature=model_options.temperature,
    top_p=model_options.top_p,
    top_k=model_options.top_k,
    num_beams=model_options.num_beams,
    max_new_tokens=model_options.max_new_tokens,
  )

  prompt = generate_prompt(model_options.instruction, model_options.input)
  inputs = tokenizer(prompt, return_tensors="pt")
  input_ids = inputs["input_ids"].cuda()


  def stream_callback(res):
    q.put(json.dumps({ "text": res }) + '\n')

  logits_processor= [CallbackLogitsWarper(tokenizer, stream_callback)] if stream else None

  def generate():
    with torch.no_grad():
      model.eval()
      model.generate(
          input_ids=input_ids,
          generation_config=generation_config,
          logits_processor=logits_processor,
          return_dict_in_generate=True,
          # output_scores=True,
          # max_new_tokens=600
      )
      print('STREAMING DONE')
    torch.cuda.empty_cache()
    q.put("[DONE]")

  # start the generate function in a new Thread so that the code doesn't stop executing here
  Thread(target=generate,args=()).start()

  while True:
    next_item = q.get(True,10000) # Blocks until an input is available
    if next_item == "[DONE]":
        yield next_item
        break
    yield next_item
```

**Comment by canonhui** [comment]
That's awesome! Solved my problem perfectly! Greatly appreciated😊

**Comment by fragro** [comment]
Looks like the issue with incomplete words has been solved with the latest PR to transformers:

https://github.com/huggingface/transformers/pull/22449

Going to give this a shot this evening.

**Comment by gante** [comment]
@fragro some extra context behind https://github.com/huggingface/transformers/pull/22449 -- different tokenizers have different strategies to stitch tokens together, so the solution I've built there is a simple heuristic that (AFAIK) works with all models/tokenizers.

If you notice it is causing slowdowns, I'm sure better model-specific strategies can be found. However, since decoding is not a heavy task, it should be fine :)
