### ISSUE TITLE
generate.py "NotImplementedError: Cannot copy out of meta tensor; no data!"

### ISSUE THREAD

**Issue by wolfscowl** [tloen/alpaca-lora#536]
Hi, 
I always get an error message when I try to generate an output (see below).

Here how it looks like if i start the default command

```shell
python generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'
``` 

![run](https://github.com/tloen/alpaca-lora/assets/64498784/52c85f90-ea6a-4d47-bafd-2edbf99eaf4c)

Here few specific key data
OS: Windows 11 Anaconda
Python: 3.9.16
CUDA: 11.7
Pytorch: 2.0.1  py3.9_cuda11.7_cudnn8_0   

When I try to generate the output via the web browser, it takes a moment and an erro appears in the web browser (see screenshot)

![error 1](https://github.com/tloen/alpaca-lora/assets/64498784/039e71a1-6a33-42a7-9c37-edf19c6cd5dc)

Here is the error from the command line;

```shell
Traceback (most recent call last):
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\interface.py", line 636, in fn
    async for output in iterator:
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "D:\LLaMA\python\finetune\alpaca-lora\generate.py", line 150, in evaluate
    generation_output = model.generate(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\peft\peft_model.py", line 627, in generate
    outputs = self.base_model.generate(**kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\generation\utils.py", line 1522, in generate
    return self.greedy_search(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\generation\utils.py", line 2339, in greedy_search
    outputs = self(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 194, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 282, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\utils\modeling.py", line 194, in set_module_tensor_to_device
    module = module.cuda(device_index)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by kaijieJiao** [comment]
hello，do you solve it? I meet the same error as your

**Comment by kaijieJiao** [comment]
> Hi, I always get an error message when I try to generate an output (see below).
> 
> Here how it looks like if i start the default command
> 
> ```shell
> python generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'
> ```
> 
> ![run](https://user-images.githubusercontent.com/64498784/250395286-52c85f90-ea6a-4d47-bafd-2edbf99eaf4c.jpg)
> 
> Here few specific key data OS: Windows 11 Anaconda Python: 3.9.16 CUDA: 11.7 Pytorch: 2.0.1 py3.9_cuda11.7_cudnn8_0
> 
> When I try to generate the output via the web browser, it takes a moment and an erro appears in the web browser (see screenshot)
> 
> ![error 1](https://user-images.githubusercontent.com/64498784/250395516-039e71a1-6a33-42a7-9c37-edf19c6cd5dc.jpg)
> 
> Here is the error from the command line;
> 
> ```shell
> Traceback (most recent call last):
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\blocks.py", line 1352, in process_api
>     result = await self.call_function(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\blocks.py", line 1093, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 341, in async_iteration
>     return await iterator.__anext__()
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\interface.py", line 636, in fn
>     async for output in iterator:
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 334, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
>     return await future
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
>     result = context.run(func, *args)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
>     return next(iterator)
>   File "D:\LLaMA\python\finetune\alpaca-lora\generate.py", line 150, in evaluate
>     generation_output = model.generate(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\peft\peft_model.py", line 627, in generate
>     outputs = self.base_model.generate(**kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\generation\utils.py", line 1522, in generate
>     return self.greedy_search(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\generation\utils.py", line 2339, in greedy_search
>     outputs = self(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 688, in forward
>     outputs = self.model(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 578, in forward
>     layer_outputs = decoder_layer(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\transformers\models\llama\modeling_llama.py", line 194, in forward
>     query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
>     args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\hooks.py", line 282, in pre_forward
>     set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\accelerate\utils\modeling.py", line 194, in set_module_tensor_to_device
>     module = module.cuda(device_index)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
>     module._apply(fn)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
>     param_applied = fn(param)
>   File "C:\Users\wolfscowl\anaconda3\envs\envLoraLab\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
> NotImplementedError: Cannot copy out of meta tensor; no data!
> ```

hello，do you solve it? I meet the same error as your

**Comment by kaijieJiao** [comment]
hello，do you solve it? I meet the same error as your@Wolfscowl

**Comment by wolfscowl** [comment]
> hello，do you solve it? I meet the same error as your@Wolfscowl

Hi, I have solved the problem.
I use an extra environment for text generation.
Here my extra anaconda environment for text generation:

```shell
# ======= envAlpacaLoraEval =======
conda create --name envAlpacaLoraEval python=3.10
conda install -c conda-forge jupyterlab
pip install scipy
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

cd alpaca-lora 
pip install -r requirements.txt
pip install git+https://github.com/Keith-Hon/bitsandbytes-windows.git
```
