### ISSUE TITLE
Error docker run

### ISSUE THREAD

**Issue by lucasezer** [tloen/alpaca-lora#547]
docker run --gpus=all --shm-size 64g -p 7860:7860 -v ${HOME}/.cache:/root/.cache --rm alpaca-lora generate.py     --load_8bit     --base_model 'decapoda-research/llama-7b-hf'     --lora_weights 'tloen/alpaca-lora-7b'

Traceback (most recent call last):
  File "/workspace/generate.py", line 5, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 42, in <module>
    from pydantic import BaseModel, parse_obj_as
  File "/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py", line 13, in <module>
    from . import dataclasses
  File "/usr/local/lib/python3.10/dist-packages/pydantic/dataclasses.py", line 11, in <module>
    from ._internal import _config, _decorators, _typing_extra
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py", line 9, in <module>
    from ..config import ConfigDict, ExtraValues, JsonSchemaExtraCallable
  File "/usr/local/lib/python3.10/dist-packages/pydantic/config.py", line 10, in <module>
    from .deprecated.config import BaseConfig
  File "/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/config.py", line 6, in <module>
    from typing_extensions import deprecated
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

**Comment by stefangweichinger** [comment]
same here. oct, 18th, fresh checkout and build

**Comment by ctborg** [comment]
Seems to be a dependency issue: https://github.com/gradio-app/gradio/issues/6068

In `requirements.txt` just lock gradio to an older version. I used `gradio==3.38.0` and it resolved.

**Comment by Linsoh181** [comment]
I have the same problem!
