### ISSUE TITLE
Is Google Cloud TPU supported?

### ISSUE THREAD

**Issue by aicheung** [tloen/alpaca-lora#58]
Hi. I got some free TPU quotas from Google and I tried to train a model on a Google Cloud TPU VM (v2-8). It can download the model but had the following error. Below are the full logs:

`$ python3 finetune.py 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
/home/aicheung/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Traceback (most recent call last):
  File "finetune.py", line 46, in <module>
    model = LlamaForCausalLM.from_pretrained(
  File "/home/aicheung/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2591, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
                        
`
Is TPU not supported? I have no experience with HuggingFace's libraries (only used Tensorflow before) so I am not sure how it works. Thanks.

**Comment by nicknitewolf** [comment]
bitsandbytes, the tool used to quantize the data set is for cuda devices only. No idea how to rework this to using tensor cores. still researching about how to use hugging face

**Comment by gkroiz** [comment]
My understanding of bitsandbytes is that it is a wrapper around custom CUDA functions. AFAIK, CUDA is specific for Nvidia GPUs and is not support on TPUs.
