### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'inputs'

### ISSUE THREAD

**Issue by Wenzhi-Ding** [tloen/alpaca-lora#605]
Hi,

I am running `python generate.py` and found that in the most recent version of `gradio`, they have changed their `gradio.inputs.Textbox` to `gradio.Textbox`, so I encountered the following errors.

```python
Traceback (most recent call last):
  File "/home/wenzhi/alpaca-lora/generate.py", line 189, in <module>
    fire.Fire(main)
  File "/home/wenzhi/miniconda3/envs/d2l/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/wenzhi/miniconda3/envs/d2l/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/wenzhi/miniconda3/envs/d2l/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/wenzhi/alpaca-lora/generate.py", line 137, in main
    gr.inputs.Textbox(
AttributeError: module 'gradio' has no attribute 'inputs'
```

Although most users should be able to fix it, I think maybe you can either update this script or specify a fixed version of `gradio` in `requirements.txt`?

**Comment by rudza** [comment]
Facing the same problem.

**Comment by Muqi-Zou** [comment]
https://github.com/gradio-app/gradio/issues/6384

**Comment by Nimisha-Pabbichetty** [comment]
I had the same issue as well, if you just want to generate outputs for some input prompts and you don't need to gradio interface then you can prompt the model like this: https://github.com/Nimisha-Pabbichetty/alpaca-lora/blob/main/generate.py

**Comment by qiye45** [comment]
I also faced the same problem. The solution that worked for me is to install an older version of Gradio.
pip install gradio==3.50

**Comment by RodolpheCalvet** [comment]
pip install gradio==3.50 was ok tks

**Comment by wanyukang** [comment]
> pip install gradio==3.50 was ok tks

Actionable suggestions, thanks for sharing

**Comment by alexandriabindas** [comment]
Downgrading to 3.5.0 works, but it does output a warning message saying that gradio.inputs will be deprecated, so importing from gradio.components instead should be another solution if you don't want to downgrade, as stated in the warning:

```
GradioDeprecationWarning: 
Usage of gradio.inputs is deprecated, and will not be supported in the future, 
please import your component from gradio.components
  gr.inputs.Textbox(
  .... 
```

**Comment by rudza** [comment]
I fixed the issues by using Components from `gradio` object directly.

**Comment by SevinduEk** [comment]
`gr.Textbox` can be used directly

**Comment by gaut9m** [comment]
I am facing the same issue and gradio==3.50 does not seem to fix it

**Comment by claverohub** [comment]
Hi! I'm very new in all of this so I'd appreciate your help.
As mention others, gradio==3.50 does not seem to fix it. After installing it, now I'm running app.py but then it shows the following message: ModuleNotFoundError: No module named 'distutils'
Python website mentions that distutils are now obsolete. So... I don't know what to do. Any idea?
Thanks!

**Comment by Wonderwill627** [comment]
This does work thanks and good luck

!pip install gradio==3.43.1

**Comment by BHEESETTIANAND** [comment]
AttributeError                            Traceback (most recent call last)
[<ipython-input-88-6cc3d65ce7f9>](https://localhost:8080/#) in <cell line: 3>()
      2 
      3 demo = gr.Interface(
----> 4     fn=classify_audio, inputs=gr.Audio(type="filepath"), outputs=gr.outputs.Label()
      5 )
      6 demo.launch(debug=True)

AttributeError: module 'gradio' has no attribute 'outputs'

**Comment by alexandriabindas** [comment]
gradio deprecated `gradio.inputs` and `gradio.ouputs`. Use `gradio.components` for newer versions. See example:

```
import gradio as gr

# Component eg. Image, Label ...etc

outputs=gr.components.<Component>(...) 
inputs=gr.components.<Component>(...)
```

**Comment by chiarapero1993** [comment]
#@title Demo UI
import gradio as gr
import numpy as np

def generate_image(seed, c0, c1, c2, c3, c4, c5, c6):
    seed = int(seed)
    params = {'c0': c0,
          'c1': c1,
          'c2': c2,
          'c3': c3,
          'c4': c4,
          'c5': c5,
          'c6': c6}

    # Assigns slider to the principal components
    param_indexes = {'c0': 0,
              'c1': 1,
              'c2': 2,
              'c3': 3,
              'c4': 4,
              'c5': 5,
              'c6': 6}

    # Save the values from the sliders
    directions = []
    distances = []
    for k, v in params.items():
        directions.append(latent_dirs[param_indexes[k]])
        distances.append(v)

    # Additional settings for image generation
    start_layer = 0
    end_layer = 14
    truncation = 0.5
    
    return display_sample_pytorch(seed, truncation, directions, distances, scale, int(start_layer), int(end_layer), disp=False)

# Create a number input for seed
seed = gr.inputs.Number(default=0, label="Seed 1")

slider_max_val = 20
slider_min_val = -20
slider_step = 1

# Create the sliders input
c0 = gr.inputs.Slider(label="Sleeve & Size", minimum=slider_min_val, maximum=slider_max_val, default=0)
c1 = gr.inputs.Slider(label="Dress - Jacket", minimum=slider_min_val, maximum=slider_max_val, default=0)
c2 = gr.inputs.Slider(label="Female Coat", minimum=slider_min_val, maximum=slider_max_val, default=0)
c3 = gr.inputs.Slider(label="Coat", minimum=slider_min_val, maximum=slider_max_val, default=0)
c4 = gr.inputs.Slider(label="Graphics", minimum=slider_min_val, maximum=slider_max_val, default=0)
c5 = gr.inputs.Slider(label="Dark", minimum=slider_min_val, maximum=slider_max_val, default=0)
c6 = gr.inputs.Slider(label="Less Cleavage", minimum=slider_min_val, maximum=slider_max_val, default=0)


inputs = [seed, c0, c1, c2, c3, c4, c5, c6]

# Launch demo
gr.Interface(generate_image, inputs, ["image"], live=True, title="ClothingGAN").launch(debug=True) 


AttributeError                            Traceback (most recent call last)
[<ipython-input-23-8ffc4d6a41d7>](https://aqpphdlb1mt-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240227-060546_RC00_610708960#) in <cell line: 39>()
     37 
     38 # Create a number input for seed
---> 39 seed = gr.inputs.Number(default=0, label="Seed 1")
     40 
     41 slider_max_val = 20

AttributeError: module 'gradio' has no attribute 'inputs'

**Comment by Alchemist21** [comment]
This is so helpful. I was able to make it work when I realized gradio deprecated input/output into simply components. Thank you again @alexandrabindas

**Comment by Elham-Keshavarz** [comment]
> pip install gradio==3.50

thank you for sharing

**Comment by OfficialLuciano** [comment]
> I also faced the same problem. The solution that worked for me is to install an older version of Gradio. pip install gradio==3.50

Thank you very much.

**Comment by sakjais** [comment]
> I fixed the issues by using Components from `gradio` object directly.

Hey, 
can you please tell the step for that

**Comment by mahmoodalikhan1999** [comment]
The error you people are encountering is due to using deprecated attribute names in Gradio. As of Gradio v3.0 and later, the module attributes inputs and outputs have been replaced with components.

You could use like gr.Textbox for both input and output

**Comment by harrison84125** [comment]
For those who want to run the **Docker Setup & Inference** in the main branch, and get a similar error.
Change line 188 in `generate.py`, which can fix a similar issue.
```python=188
            gr.inputs.Textbox(
                lines=5,
                label="Output",
            )
```
```python=188
            gr.Textbox(
                lines=5,
                label="Output",
            )
```

**Comment by welew204** [comment]
> gradio deprecated `gradio.inputs` and `gradio.ouputs`. Use `gradio.components` for newer versions. See example:
> 
> ```
> import gradio as gr
> 
> # Component eg. Image, Label ...etc
> 
> outputs=gr.components.<Component>(...) 
> inputs=gr.components.<Component>(...)
> ```

And actually, [Gradio docs](https://www.gradio.app/docs/gradio/image) just recommend `gr.<Component>. ...`
