### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### ISSUE THREAD

**Issue by mj2688** [tloen/alpaca-lora#609]
When I fine-tune llama2-7B with LoRa, the following error occurs:
Traceback (most recent call last):
  File "/home/ubuntu/lora/alpaca-lora-main/finetune.py", line 290, in <module>
    fire.Fire(train)
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/lora/alpaca-lora-main/finetune.py", line 280, in train
    trainer.train()
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/transformers/trainer.py", line 1965, in _inner_training_loop
    self._load_best_model()
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/transformers/trainer.py", line 2184, in _load_best_model
    model.load_adapter(self.state.best_model_checkpoint, model.active_adapter)
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/peft/peft_model.py", line 629, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/peft/utils/save_and_load.py", line 222, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "/home/ubuntu/anaconda3/envs/loar/lib/python3.9/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

![image](https://github.com/tloen/alpaca-lora/assets/144690766/3d30ac0e-6ea1-4774-a19c-eaa8a2960858)

And in checkpoint-1000, adapter_model.safetensors is saved in the .safetensors format. I checked the official fine-tuning weights, and they are in the adapter_model.bin format. Why is that?

**Comment by RiccardoIzzo** [comment]
I'm currently having the same problem. Are you using a well known dataset (such as alpaca) or a custom one? @mj2688  By the way I noticed that with few epochs this doesn't happen.

**Comment by mj2688** [comment]
> I'm currently having the same problem. Are you using a well known dataset (such as alpaca) or a custom one? @mj2688 By the way I noticed that with few epochs this doesn't happen.
I use the same dataset in the example code(finetune.py).

data_path: str = "yahma/alpaca-cleaned"

I referred to this tutorial and deleted 'torch.compile' in finetune.py , but it still not works.
https://github.com/huggingface/transformers/issues/27397

**Comment by RiccardoIzzo** [comment]
You can find the fix reported in this [issue](https://github.com/slai-labs/get-beam/issues/94). This solved the InvalidHeaderDeserialization error for me.

**Comment by Concyclics** [comment]
Have u fix this problem? I'm current facing the same?

**Comment by RiccardoIzzo** [comment]
Yes, I solved. You have to comment these lines in [finetune.py](https://github.com/tloen/alpaca-lora/blob/8bb8579e403dc78e37fe81ffbb253c413007323f/finetune.py#L264-L271).
The reason is that currently there is an incompatibility between PyTorch and PEFT library as reported [here](https://github.com/huggingface/transformers/issues/27397).

**Comment by mj2688** [comment]
> Yes, I solved. You have to comment these lines in [finetune.py](https://github.com/tloen/alpaca-lora/blob/8bb8579e403dc78e37fe81ffbb253c413007323f/finetune.py#L264-L271). The reason is that currently there is an incompatibility between PyTorch and PEFT library as reported [here](https://github.com/huggingface/transformers/issues/27397).

thanks,i also solved!

**Comment by mj2688** [comment]
> Have u fix this problem? I'm current facing the same?

delete some codes in finetune.py : 
    model.state_dict = (
        lambda self, *_, **__: get_peft_model_state_dict(
            self, old_state_dict()
        )
    ).__get__(model, type(model))

    if torch.__version__ >= "2" and sys.platform != "win32":
        model = torch.compile(model)

**Comment by nihaowz** [comment]
> > Have u fix this problem? I'm current facing the same?
> 
> delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> 
> ```
> if torch.__version__ >= "2" and sys.platform != "win32":
>     model = torch.compile(model)
> ```

But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

**Comment by MING8276** [comment]
> > > Have u fix this problem? I'm current facing the same?
> > 
> > 
> > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > ```
> > if torch.__version__ >= "2" and sys.platform != "win32":
> >     model = torch.compile(model)
> > ```
> 
> But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

Hi. I think the .safetensors file is not compatible with PEFT，so I delete the xx.safetensors file and it works.

**Comment by nihaowz** [comment]
> > > > Have u fix this problem? I'm current facing the same?
> > > 
> > > 
> > > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > > ```
> > > if torch.__version__ >= "2" and sys.platform != "win32":
> > >     model = torch.compile(model)
> > > ```
> > 
> > 
> > But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
> 
> Hi. I think the .safetensors file is not compatible with PEFT，so I delete the xx.safetensors file and it works.


Do you mean to delete the file after fine-tuning and run it now.Is this file an adapter_ model. safetensors

**Comment by mj2688** [comment]
> > > > > Have u fix this problem? I'm current facing the same?
> > > > 
> > > > 
> > > > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > > > ```
> > > > if torch.__version__ >= "2" and sys.platform != "win32":
> > > >     model = torch.compile(model)
> > > > ```
> > > 
> > > 
> > > But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
> > 
> > 
> > Hi. I think the .safetensors file is not compatible with PEFT，so I delete the xx.safetensors file and it works.
> 
> Do you mean to delete the file after fine-tuning and run it now.Is this file an adapter_ model. safetensors

Before fine-tuning,i delete this,then it works:
model.state_dict = (
lambda self, *_, **__: get_peft_model_state_dict(
self, old_state_dict()
)
).get(model, type(model))

if torch.__version__ >= "2" and sys.platform != "win32":
    model = torch.compile(model)

**Comment by nihaowz** [comment]
> > > > > > Have u fix this problem? I'm current facing the same?
> > > > > 
> > > > > 
> > > > > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > > > > ```
> > > > > if torch.__version__ >= "2" and sys.platform != "win32":
> > > > >     model = torch.compile(model)
> > > > > ```
> > > > 
> > > > 
> > > > But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
> > > 
> > > 
> > > Hi. I think the .safetensors file is not compatible with PEFT，so I delete the xx.safetensors file and it works.
> > 
> > 
> > Do you mean to delete the file after fine-tuning and run it now.Is this file an adapter_ model. safetensors
> 
> Before fine-tuning,i delete this,then it works: model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).get(model, type(model))
> 
> if torch.**version** >= "2" and sys.platform != "win32": model = torch.compile(model)

I've tried it before, but it still doesn't work

**Comment by tamanna-mostafa** [comment]
I'm having this same issue (details here: https://github.com/huggingface/transformers/issues/28742). Could anyone please help?

**Comment by tamanna-mostafa** [comment]
> > > > Have u fix this problem? I'm current facing the same?
> > > 
> > > 
> > > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > > ```
> > > if torch.__version__ >= "2" and sys.platform != "win32":
> > >     model = torch.compile(model)
> > > ```
> > 
> > 
> > But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
> 
> Hi. I think the .safetensors file is not compatible with PEFT，so I delete the xx.safetensors file and it works.

@MING8276 Would you mind telling me what files you deleted?

**Comment by SHUSHENGQIGUI** [comment]
> > > Have u fix this problem? I'm current facing the same?
> > 
> > 
> > delete some codes in finetune.py : model.state_dict = ( lambda self, *_, **__: get_peft_model_state_dict( self, old_state_dict() ) ).**get**(model, type(model))
> > ```
> > if torch.__version__ >= "2" and sys.platform != "win32":
> >     model = torch.compile(model)
> > ```
> 
> But if I delete the above, it still exists safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

**do you solve this problem? i meet the same problem.**
